### PR TITLE
New message :)

### PR DESCRIPTION
**Pull request by tberster**

### CODE REVIEW

**Review by wangdrew — APPROVED** [review]

**Comment by enachb** [comment]
Are you guys learning Git & Github? Very fundamental changes going on here...

**Comment by opsroller** [comment]
@enachb haha we put a crony an onto chesters computer that runs every few minutes and calls “ say the contents of the file”

**Comment by enachb** [comment]
Still? Wasn't that a thing when he was at VPS?

**Comment by opsroller** [comment]
Yes, that’s why I’m laughing at the fact that this repo is still getting pull requests!

**Pull request merged**
